name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: 'self-hosted'
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images         
    - name: Deploy to minikube
      run:
        kubectl apply -f k8s-node-app.yaml
    - name: get service details
      run:
        kubectl get service
    - name: get pod logs
      run:
        kubectl get pods
    - name: sleep for 2 min
      run:
        sleep 120
    
    - name: Test service URLs
      run: |
          minikube service list 
          minikube service nodejs-app --url
    
    - name: Harness Deploy Action
      id: deploy
      uses: fac/harness-deploy-action@v1.0
      with:
        webhookUrl: ${{secrets.HARNESS_WEBHOOK_URL }}
        application: 
        services: 
        version: ${{ github.sha }}
        harnessApiKey: ${{ secrets.HARNESS_API_KEY }}
    - name: Deploy Link
      run: |
         echo harness_url: ${{ steps.deploy.outputs.harness_url }}
     
    
